PACKAGE_BASE_DEVELOPMENT=""
PACKAGE_DOCKER=""
PACKAGE_FLATPAK=""
PACKAGE_GIMP=""
PACKAGE_JAVA=""
PACKAGE_LIB_ARCHIVE=""
PACKAGE_LIB_CRYPTO=""
PACKAGE_LIB_CURL=""
PACKAGE_LIB_FFI=""
PACKAGE_NETWORK_BUNDLE=""
PACKAGE_NMAP=""
PACKAGE_PYTHON=""
PACKAGE_REMMINA=""
PACKAGE_RUST=""
PACKAGE_SIMPLE_SCREEN_RECORDER=""
PACKAGE_WIRESHARK=""

if binary_exists swupd
then
    PACKAGE_BASE_DEVELOPMENT="dev-utils"
    PACKAGE_DOCKER="docker-compose"
    PACKAGE_FLATPAK="flatpak"
    PACKAGE_GIMP="gimp"
    PACKAGE_JAVA="java-basic"
    PACKAGE_LIB_ARCHIVE="devpkg-libarchive"
    PACKAGE_LIB_CRYPTO="devpkg-openssl"
    PACKAGE_LIB_CURL="devpkg-curl"
    PACKAGE_LIB_FFI="devpkg-libffi"
    PACKAGE_NETWORK_BUNDLE="network-basic"
    PACKAGE_NMAP="nmap"
    PACKAGE_PYTHON="python3-basic"
    PACKAGE_REMMINA="Remmina"
    PACKAGE_RUST="rust-basic"
    PACKAGE_SIMPLE_SCREEN_RECORDER="simplescreenrecorder"
    PACKAGE_WIRESHARK="wireshark"
elif binary_exists apt
then
    PACKAGE_BASE_DEVELOPMENT="build-essential"
    PACKAGE_DOCKER="docker-compose"
    PACKAGE_FLATPAK="flatpak"
    PACKAGE_GIMP="gimp"
    PACKAGE_JAVA="default-jdk"
    PACKAGE_LIB_ARCHIVE="libarchive-dev"
    PACKAGE_LIB_CRYPTO="libssl-dev"
    PACKAGE_LIB_CURL="libcurl4-openssl-dev whois"
    PACKAGE_LIB_FFI="libffi-dev http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb"
    PACKAGE_NETWORK_BUNDLE="bind9-dnsutils iputils-ping whois"
    PACKAGE_NMAP="nmap"
    PACKAGE_PYTHON="python3-pip python-is-python3"
    PACKAGE_REMMINA="remmina remmina-plugin-rdp remmina-plugin-secret"
    PACKAGE_RUST="cargo"
    PACKAGE_SIMPLE_SCREEN_RECORDER="simplescreenrecorder"
    PACKAGE_WIRESHARK="wireshark"
fi
